# Generated by Django 3.0.5 on 2020-05-26 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Usuario')),
            ],
            options={
                'db_table': 'tbPaciente',
            },
            bases=('core.usuario',),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='perfil',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rg',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone_celular',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone_fixo',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateField()),
                ('colaborador', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Colaborador')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Paciente')),
            ],
            options={
                'db_table': 'tbAtendimento',
            },
        ),
    ]
