# Generated by Django 3.0.5 on 2020-06-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200605_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='foto',
            field=models.ImageField(default='imagens/None/no-img.jpg', upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, null=True),
        ),
    ]
