# Generated by Django 3.0.5 on 2020-06-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200620_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado'), ('ACEITO', 'Aceito'), ('ANALISE', 'Em Análise')], max_length=50),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tipo',
            field=models.CharField(choices=[('PLANTAO', 'Plantão'), ('PSICOTERAPIA', 'Psicoterapia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[(7, 'Sábado'), (3, 'Terça-Feira'), (4, 'Quarta-Feira'), (5, 'Quinta-Feira'), (6, 'Sexta-Feira'), (1, 'Domingo'), (2, 'Segunda-Feira')], max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='orientacao_sexual',
            field=models.CharField(choices=[('INDEFINIDO', 'Prefiro não informar'), ('HOMO', 'Homossexual'), ('HETERO', 'Heterossexual'), ('BI', 'Bissexual')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=1, null=True),
        ),
        migrations.AlterModelTable(
            name='especialidade',
            table='tbEspecialidade',
        ),
    ]
