# Generated by Django 3.0.5 on 2020-06-20 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200620_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='colaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agendamentos', to='core.Colaborador'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agendamentos', to='core.Paciente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('CANCELADO', 'Cancelado'), ('ACEITO', 'Aceito'), ('REALIZADO', 'Realizado'), ('ANALISE', 'Em Análise')], max_length=50),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[(7, 'Sábado'), (6, 'Sexta-Feira'), (1, 'Domingo'), (4, 'Quarta-Feira'), (3, 'Terça-Feira'), (5, 'Quinta-Feira'), (2, 'Segunda-Feira')], max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='orientacao_sexual',
            field=models.CharField(choices=[('BI', 'Bissexual'), ('HETERO', 'Heterossexual'), ('INDEFINIDO', 'Prefiro não informar'), ('HOMO', 'Homossexual')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('O', 'Outro'), ('F', 'Feminino')], max_length=1, null=True),
        ),
    ]
